### ISSUE TITLE
[p0] todo list

### ISSUE THREAD

**Issue by xiaohuoni** [alitajs/valita#1]
## p0
- [x] [Vant]()
- [x] [数据流 pinia](https://pinia.vuejs.org/) @xiaohuoni https://github.com/alitajs/valita/pull/2 3.5h
- [x] [布局和菜单]() #3 
- [x] [国际化(多语言)]() https://github.com/alitajs/valita/pull/9
- [x] [请求库、请求方案]() @xiaohuoni https://github.com/alitajs/valita/pull/8
- [x] [自动导入 auto Import]() @xiaohuoni https://github.com/alitajs/valita/pull/11
- [x] [README]() @xiaohuoni 第一个版本的 README https://github.com/alitajs/valita/pull/14
- [x] [keepalive] @hang1017 https://github.com/alitajs/valita/pull/16
## 其他可选
[权限]()
[图表]()
[乾坤微前端]()
[Tailwind CSS]()
[CSS-IN-JS]()
